### ISSUE TITLE
Problems displaying umlauts / special characters

### ISSUE THREAD

**Issue by lclc** [RCasatta/Geobit#17]
All the ä, ö, ü etc. we use in German aren't displayed correctly.

**Comment by RCasatta** [comment]
Does this happen on coinmap imported elements (the white one), right?

**Comment by lclc** [comment]
Yes. I didn't try with others yet.

**Comment by RCasatta** [comment]
fixed encoding returned by server to utf-8
italian accented letters looks ok, german should too
